sudo: true
language: node_js
node_js:
  - "stable"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install chromium-browser firefox
install:
  - npm install -g grunt-cli
  - npm install karma karma-firefox-launcher karma-chrome-launcher karma-jasmine
  - npm install
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - grunt
  - grunt test
  - ./node_modules/.bin/karma start
